[package]
name = "syntree-layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
syntree = "0.14.1"
thiserror = "1.0.38"
xml_writer = "0.4.0"
